# Use root/example as user/password credentials
version: '3.1'

services:

  auth-service:
    image: auth-service
    container_name: express-auth-service
    build:
      context: ./auth
      target: dev
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://authuser:authpassword@express-auth-service-nosql:27017/authy
      - PORT=3000
      - ACCESS_TOKEN_SECRET=accessToKenSecret
      - REFRESH_TOKEN_SECRET=refreshToKenSecret
    networks:
      - lab-network

  mongo:
    image: mongo
    container_name: express-auth-service-nosql
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=authy
      - MONGO_INITDB_USERNAME=authuser
      - MONGO_INITDB_PASSWORD=authpassword
    volumes:
      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongo/db:/data/db
    networks:
      - lab-network

networks:
  lab-network:
    external: true