# Use root/example as user/password credentials
version: '3.1'

services:

  auth-service:
    image: auth-service
    container_name: express-auth-service
    build:
      context: ./auth
      target: dev
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://authy:abcd1234@express-auth-service-nosql:27017/authy
      - PORT=3000
    networks:
      - lab-network

  mongo:
    image: mongo
    container_name: express-auth-service-nosql
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: authy
    networks:
      - lab-network

networks:
  lab-network:
    external: true